const img = {
    hotline: require("./hotline.png"),
    deal: require("./deal.png"),
    register: require("./register.png"),
    introduceBanner: require("./fpt.vn.jpg"),
    combo: require("./combo.png"),
    private: require("./quang-ca-nhan.png"),
    fptPlay: require("./fptPlay.jpg"),
    leftLine: require("./leftLine.svg").default,
    rightLine: require("./rightLine.svg").default,
    line: require("./sapeLine.svg").default,
    vipRight: require("./vipRight.jpg"),
    vipLeft: require("./leftVip.jpg"),
    maxLeft: require("./maxLeft.jpg"),
    maxRight: require("./maxRight.jpg"),
    sportRight: require("./sportRight.jpg"),
    sportLeft: require("./sportLeft.jpg"),
    kRight: require("./k+Right.jpg"),
    kLeft: require("./k+Left.jpg"),
    playboxHbo: require("./playboxHbo.jpg"),
    playboxTvShow: require("./playboxTvshow.png"),
    playboxSport: require("./playboxSport.jpg"),
    playboxAds: require("./playboxAds.jpg"),
    playboxCinema: require("./playboxCinema.jpg"),
    playboxFilm: require("./playboxFilm.jpg"),
    bannerFptPlay: require("./bannerFptPlay.jpg"),
};

export default img;
